### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by darceno** [Miki-Tellurium/ClockOverlay#1]
I'm loving your mod! I'm trying to play in a more vanilla-immersive style and it's helping me get rid of needing to use F3. Thank you so much for making it.

I think it would be very cool if, besides the time, the clock also displayed the day count of the world. This way, it would replace the F3 for good when it comes to time-related info.

This is suggestion 1. Suggestion 2 is related but beyond this mod: would you consider making a mod just like this, but for the compass instead? I'd love to use it alongside Clock Overlay.

I know there are some others out there that do similar things, but none works exactly the way Clock Overlay does, which I like because it matches the behavior of the Altimeter item in the Supplementaries mod, which helps with consistency.

Thank you again.

**Comment by Miki-Tellurium** [comment]
Thank you for the suggestions! The first one should be fairly easy to add, and I already planned to add that at some point. The second one is an interesting idea, it will require a bit of time because I have to figure out how to implement it since the player can have different compass pointing in different directions. Right now I'm busy studying but once I have free time again I'll work on it.

**Comment by Miki-Tellurium** [comment]
Also I closed this by mistake. GitHub from mobile is a bit confusing.

**Comment by darceno** [comment]
Haha, no worries!

About the compass mod, the way I imagined it working was just showing the X and Z coordinates above the hotbar whenever the player right-clicked with a compass in their hand. With my very _limited_ knowledge about modding, I thought the code for that would look very similar to the Clock Overlay's code.

But of course, take your time. I'm already very grateful for you considering it!

**Comment by Miki-Tellurium** [comment]
Good news!
Check the new Clock Overlay version on Modrinth:
https://modrinth.com/mod/clock-overlay/version/1.4.0-1.21

**Comment by darceno** [comment]
Great! Thank you for your work!
